adminUser:
  password: vault:activiti-cloud/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: serverlessbot726@gmail.com
  token: vault:activiti-cloud/pipelineUser:token
  username: serverless-bot-726
prow:
  hmacToken: vault:activiti-cloud/prow:hmacToken
